#!/bin/bash

#python analyseOTPhysicsDataForLadder.py -c Configs_OTPhysics/config__1kHz__0_sigma__Ladder__lpGBT_v1__12_Mods__p15.yaml
#python analyseOTPhysicsDataForLadder.py -c Configs_OTPhysics/config__1kHz__1_sigma__Ladder__lpGBT_v1__12_Mods__p15.yaml
#python analyseOTPhysicsDataForLadder.py -c Configs_OTPhysics/config__1kHz__2_sigma__Ladder__lpGBT_v1__12_Mods__p15.yaml
#python analyseOTPhysicsDataForLadder.py -c Configs_OTPhysics/config__1kHz__3_sigma__Ladder__lpGBT_v1__12_Mods__p15.yaml

#python analyseOTPhysicsDataForLadder.py -c Configs_OTPhysics/config__1kHz__0_sigma__Ladder__lpGBT_v2__12_Mods__p15.yaml
#python analyseOTPhysicsDataForLadder.py -c Configs_OTPhysics/config__1kHz__1_sigma__Ladder__lpGBT_v2__12_Mods__p15.yaml
#python analyseOTPhysicsDataForLadder.py -c Configs_OTPhysics/config__1kHz__2_sigma__Ladder__lpGBT_v2__12_Mods__p15.yaml
#python analyseOTPhysicsDataForLadder.py -c Configs_OTPhysics/config__1kHz__3_sigma__Ladder__lpGBT_v2__12_Mods__p15.yaml


#python3 analyseOTPhysics.py -c Configs_OTPhysics/config__1kHz__0_sigma__Ladder_minus_6CP_1__pos_1__12_Mods__p15__unsparsified.yaml -s 10000
#python3 analyseOTPhysics.py -c Configs_OTPhysics/config__1kHz__1_sigma__Ladder_minus_6CP_1__pos_1__12_Mods__p15__unsparsified.yaml -s 10000
#python3 analyseOTPhysics.py -c Configs_OTPhysics/config__1kHz__2_sigma__Ladder_minus_6CP_1__pos_1__12_Mods__p15__unsparsified.yaml -s 10000
#python3 analyseOTPhysics.py -c Configs_OTPhysics/config__1kHz__3_sigma__Ladder_minus_6CP_1__pos_1__12_Mods__p15__unsparsified.yaml -s 40000
#python3 analyseOTPhysics.py -c Configs_OTPhysics/config__1kHz__4_sigma__Ladder_minus_6CP_1__pos_1__12_Mods__p15__unsparsified.yaml
#python3 analyseOTPhysics.py -c Configs_OTPhysics/config__1kHz__5_sigma__Ladder_minus_6CP_1__pos_1__12_Mods__p15__unsparsified.yaml

#python3 analyseOTPhysics.py -c Configs_OTPhysics/config__1kHz__0_sigma__Ladder_minus_6CP_5__pos_2__12_Mods__p15__unsparsified.yaml -s 10000
#python3 analyseOTPhysics.py -c Configs_OTPhysics/config__1kHz__1_sigma__Ladder_minus_6CP_5__pos_2__12_Mods__p15__unsparsified.yaml -s 10000
#python3 analyseOTPhysics.py -c Configs_OTPhysics/config__1kHz__2_sigma__Ladder_minus_6CP_5__pos_2__12_Mods__p15__unsparsified.yaml -s 10000
#python3 analyseOTPhysics.py -c Configs_OTPhysics/config__1kHz__3_sigma__Ladder_minus_6CP_5__pos_2__12_Mods__p15__unsparsified.yaml -s 40000
#python3 analyseOTPhysics.py -c Configs_OTPhysics/config__1kHz__4_sigma__Ladder_minus_6CP_5__pos_2__12_Mods__p15__unsparsified.yaml
#python3 analyseOTPhysics.py -c Configs_OTPhysics/config__1kHz__5_sigma__Ladder_minus_6CP_5__pos_2__12_Mods__p15__unsparsified.yaml


#python3 analyseOTPhysics.py -c Configs_OTPhysics/config__10kHz__3_sigma__KIRA__lpGBT_v1__1_Mods__p15__unsparsified_default_1.yaml
#python3 analyseOTPhysics.py -c Configs_OTPhysics/config__10kHz__3_sigma__KIRA__lpGBT_v1__1_Mods__p15__unsparsified_default_2.yaml
#python3 analyseOTPhysics.py -c Configs_OTPhysics/config__10kHz__3_sigma__KIRA__lpGBT_v1__1_Mods__p15__unsparsified_default_3.yaml
#python3 analyseOTPhysics.py -c Configs_OTPhysics/config__10kHz__3_sigma__KIRA__lpGBT_v1__1_Mods__p15__unsparsified_default_4.yaml
#python3 analyseOTPhysics.py -c Configs_OTPhysics/config__10kHz__3_sigma__KIRA__lpGBT_v1__1_Mods__p15__unsparsified_default_5.yaml
#python3 analyseOTPhysics.py -c Configs_OTPhysics/config__10kHz__3_sigma__KIRA__lpGBT_v1__1_Mods__p15__unsparsified_delay_1.yaml
#python3 analyseOTPhysics.py -c Configs_OTPhysics/config__10kHz__3_sigma__KIRA__lpGBT_v1__1_Mods__p15__unsparsified_delay_2.yaml


#python3 analyseOTPhysics.py -c Configs_OTPhysics/config__5kHz__2_sigma__KIRA__lpGBT_v1__1_Mods__p15__unsparsified_default_1.yaml
#python3 analyseOTPhysics.py -c Configs_OTPhysics/config__5kHz__2_sigma__KIRA__lpGBT_v1__1_Mods__p15__unsparsified_default_2.yaml
#python3 analyseOTPhysics.py -c Configs_OTPhysics/config__5kHz__2_sigma__KIRA__lpGBT_v1__1_Mods__p15__unsparsified_default_3.yaml
#python3 analyseOTPhysics.py -c Configs_OTPhysics/config__5kHz__2_sigma__KIRA__lpGBT_v1__1_Mods__p15__unsparsified_default_4.yaml


#python3 analyseOTPhysics.py -c Configs_OTPhysics/config__5kHz__2_sigma__KIRA__lpGBT_v1__1_Mods__p15__unsparsified_delay_1.yaml
#python3 analyseOTPhysics.py -c Configs_OTPhysics/config__5kHz__2_sigma__KIRA__lpGBT_v1__1_Mods__p15__unsparsified_delay_2.yaml
#python3 analyseOTPhysics.py -c Configs_OTPhysics/config__5kHz__2_sigma__KIRA__lpGBT_v1__1_Mods__p15__unsparsified_delay_3.yaml

python3 analyseOTPhysics.py -c Configs_OTPhysics/config__5kHz__2_sigma__KIRA__lpGBT_v1__1_Mods__p15__unsparsified_DLL_1.yaml
python3 analyseOTPhysics.py -c Configs_OTPhysics/config__5kHz__2_sigma__KIRA__lpGBT_v1__1_Mods__p15__unsparsified_DLL_2.yaml
python3 analyseOTPhysics.py -c Configs_OTPhysics/config__5kHz__2_sigma__KIRA__lpGBT_v1__1_Mods__p15__unsparsified_DLL_3.yaml
