#!/bin/bash

python analyseOTPhysicsDataForLadder.py -c Configs_OTPhysics/config__1kHz__0_sigma__Ladder__lpGBT_v1__12_Mods__p15.yaml
python analyseOTPhysicsDataForLadder.py -c Configs_OTPhysics/config__1kHz__1_sigma__Ladder__lpGBT_v1__12_Mods__p15.yaml
python analyseOTPhysicsDataForLadder.py -c Configs_OTPhysics/config__1kHz__2_sigma__Ladder__lpGBT_v1__12_Mods__p15.yaml
python analyseOTPhysicsDataForLadder.py -c Configs_OTPhysics/config__1kHz__3_sigma__Ladder__lpGBT_v1__12_Mods__p15.yaml

python analyseOTPhysicsDataForLadder.py -c Configs_OTPhysics/config__1kHz__0_sigma__Ladder__lpGBT_v2__12_Mods__p15.yaml
python analyseOTPhysicsDataForLadder.py -c Configs_OTPhysics/config__1kHz__1_sigma__Ladder__lpGBT_v2__12_Mods__p15.yaml
python analyseOTPhysicsDataForLadder.py -c Configs_OTPhysics/config__1kHz__2_sigma__Ladder__lpGBT_v2__12_Mods__p15.yaml
python analyseOTPhysicsDataForLadder.py -c Configs_OTPhysics/config__1kHz__3_sigma__Ladder__lpGBT_v2__12_Mods__p15.yaml
