# some basic info

INPUT_FILE    : "/Users/gsaha/Work/IPHC/TrackerUpgrade/Inputs/Run_3/Results.root"
OUTPUT_PATH   : "/Users/gsaha/Work/IPHC/TrackerUpgrade/Output/Split_output"

# Ladder Info
LADDER_NO   : 5
LADDER_POS  : "Zplus" # "Zminus"

# Temperature
COOLING_TEMP : "+15deg" # "0deg", "-30deg"

# Module positions
MODULE_POS:
  OpticalGroup_0  : 2S_18_6_BRN-10011
  OpticalGroup_1  : 2S_18_6_AAC-10002
  OpticalGroup_2  : 2S_18_6_AAC-10038 # one screw not connected : recommended (broken bridge)
  OpticalGroup_3  : 2S_18_6_AAC-10004
  OpticalGroup_4  : 2S_18_6_AAC-10027
  OpticalGroup_5  : 2S_18_6_AAC-10005
  OpticalGroup_6  : 2S_18_6_AAC-10003
  OpticalGroup_7  : 2S_18_5_NCP-10001
  OpticalGroup_8  : 2S_18_5_NCP-10005
  OpticalGroup_9  : 2S_18_5_NCP-10004
  OpticalGroup_10 : 2S_18_6_AAC-10006
  OpticalGroup_11 : 2S_18_5_NCP-10003
