maintag: DB_singleModuleBox

ladder: no
single_module_box: yes

n_boards: 1
n_opticals: 1


# strip noise histogram names (hybrid level)
strip_noise_hname_hybrid_level:
 - HybridStripNoiseDistribution
 - StripChannelNoise
strip_noise_hname_hybrid_level_bottom:
 - HybridNoiseBottomDistribution
 - StripChannelNoiseBottom
strip_noise_hname_hybrid_level_top:
 - HybridNoiseTopDistribution
 - StripChannelNoiseTop

# strip noise histogram names (chip level)
strip_noise_hname_chip_level:
 - ChannelNoiseDistribution
 - ChannelNoise
strip_noise_hname_chip_level_bottom:
 - ChannelNoiseBottomDistribution
 - ChannelNoiseBottom
strip_noise_hname_chip_level_top:
 - ChannelNoiseTopDistribution
 - ChannelNoiseTop

# common noise histogram names (hybrid level)
common_noise_hname_hybrid_level:
 - HybridHits
common_noise_hname_hybrid_level_bottom:
 - HybridHitsBottom
common_noise_hname_hybrid_level_top:
 - HybridHitsTop

# common noise histogram names (chip level)
common_noise_hname_chip_level:
 - ChipHits
common_noise_hname_chip_level_bottom:
 - ChipHitsBottom
common_noise_hname_chip_level_top:
 - ChipHitsTop

# common noise module level
common_noise_hname_module_level:
 - ModuleHits
common_noise_hname_module_level_bottom:
 - ModuleHitsBottom
common_noise_hname_module_level_top:
 - ModuleHitsTop


files:
  2S_18_6_BRN-10011:
    Run1:
      tfile_main: /Users/gsaha/Work/IPHC/TrackerUpgrade/Inputs/Ladder_5_DCA/2S_18_6_BRN_10011_DCA_BRN.root
      tfile_dqm: /Users/gsaha/Work/IPHC/TrackerUpgrade/Inputs/Ladder_5_DCA/2S_18_6_BRN_10011_DCA_BRN.root
  2S_18_6_AAC-10002:
    Run1:
      tfile_main: /Users/gsaha/Work/IPHC/TrackerUpgrade/Inputs/Ladder_5_DCA/2S_18_6_AAC-10002_DCA_Aachen.root
      tfile_dqm: /Users/gsaha/Work/IPHC/TrackerUpgrade/Inputs/Ladder_5_DCA/2S_18_6_AAC-10002_DCA_Aachen.root
  2S_18_6_AAC-10038:
    Run1:
      tfile_main: /Users/gsaha/Work/IPHC/TrackerUpgrade/Inputs/Ladder_5_DCA/2S_18_6_AAC-10038_DCA_Aachen.root
      tfile_dqm: /Users/gsaha/Work/IPHC/TrackerUpgrade/Inputs/Ladder_5_DCA/2S_18_6_AAC-10038_DCA_Aachen.root
  2S_18_6_AAC-10004:
    Run1:
      tfile_main: /Users/gsaha/Work/IPHC/TrackerUpgrade/Inputs/Ladder_5_DCA/2S_18_6_AAC-10004_DCA_Aachen.root
      tfile_dqm: /Users/gsaha/Work/IPHC/TrackerUpgrade/Inputs/Ladder_5_DCA/2S_18_6_AAC-10004_DCA_Aachen.root
  2S_18_6_AAC-10027:
    Run1:
      tfile_main: /Users/gsaha/Work/IPHC/TrackerUpgrade/Inputs/Ladder_5_DCA/2S_18_6_AAC-10027_DCA_Aachen.root
      tfile_dqm: /Users/gsaha/Work/IPHC/TrackerUpgrade/Inputs/Ladder_5_DCA/2S_18_6_AAC-10027_DCA_Aachen.root
  2S_18_6_AAC-10005:
    Run1:
      tfile_main: /Users/gsaha/Work/IPHC/TrackerUpgrade/Inputs/Ladder_5_DCA/2S_18_6_AAC-10005_DCA_Aachen.root
      tfile_dqm: /Users/gsaha/Work/IPHC/TrackerUpgrade/Inputs/Ladder_5_DCA/2S_18_6_AAC-10005_DCA_Aachen.root
  2S_18_6_AAC-10003:
    Run1:
      tfile_main: /Users/gsaha/Work/IPHC/TrackerUpgrade/Inputs/Ladder_5_DCA/2S_18_6_AAC-10003_DCA_Aachen.root
      tfile_dqm: /Users/gsaha/Work/IPHC/TrackerUpgrade/Inputs/Ladder_5_DCA/2S_18_6_AAC-10003_DCA_Aachen.root
  2S_18_5_NCP-10001:
    Run1:
      tfile_main: /Users/gsaha/Work/IPHC/TrackerUpgrade/Inputs/Ladder_5_DCA/2S_18_5_NCP-10001_DCA_NCP.root
      tfile_dqm: /Users/gsaha/Work/IPHC/TrackerUpgrade/Inputs/Ladder_5_DCA/2S_18_5_NCP-10001_DCA_NCP.root
  2S_18_5_NCP-10005:
    Run1:
      tfile_main: /Users/gsaha/Work/IPHC/TrackerUpgrade/Inputs/Ladder_5_DCA/2S_18_5_NCP-10005_DCA_NCP.root
      tfile_dqm: /Users/gsaha/Work/IPHC/TrackerUpgrade/Inputs/Ladder_5_DCA/2S_18_5_NCP-10005_DCA_NCP.root
  2S_18_5_NCP-10004:
    Run1:
      tfile_main: /Users/gsaha/Work/IPHC/TrackerUpgrade/Inputs/Ladder_5_DCA/2S_18_5_NCP-10004_DCA_NCP.root
      tfile_dqm: /Users/gsaha/Work/IPHC/TrackerUpgrade/Inputs/Ladder_5_DCA/2S_18_5_NCP-10004_DCA_NCP.root
  2S_18_6_AAC-10006:
    Run1:
      tfile_main: /Users/gsaha/Work/IPHC/TrackerUpgrade/Inputs/Ladder_5_DCA/2S_18_6_AAC-10006_DCA_Aachen.root
      tfile_dqm: /Users/gsaha/Work/IPHC/TrackerUpgrade/Inputs/Ladder_5_DCA/2S_18_6_AAC-10006_DCA_Aachen.root
  2S_18_5_NCP-10003:
    Run1:
      tfile_main: /Users/gsaha/Work/IPHC/TrackerUpgrade/Inputs/Ladder_5_DCA/2S_18_5_NCP-10003_DCA_NCP.root
      tfile_dqm: /Users/gsaha/Work/IPHC/TrackerUpgrade/Inputs/Ladder_5_DCA/2S_18_5_NCP-10003_DCA_NCP.root

output: /Users/gsaha/Work/IPHC/TrackerUpgrade/Output