maintag: DB_SingleModuleBox

ladder: no
single_module_box: yes

n_boards: 1
n_opticals: 1


# strip noise histogram names (hybrid level)
strip_noise_hname_hybrid_level:
 - HybridStripNoiseDistribution
strip_noise_hname_hybrid_level_bottom:
 - HybridNoiseBottomDistribution 
strip_noise_hname_hybrid_level_top:
 - HybridNoiseTopDistribution

# strip noise histogram names (chip level)
strip_noise_hname_chip_level:
 - ChannelNoiseDistribution
strip_noise_hname_chip_level_bottom:
 - ChannelNoiseBottomDistribution
strip_noise_hname_chip_level_top:
 - ChannelNoiseTopDistribution

# common noise histogram names (hybrid level)
common_noise_hname_hybrid_level:
 - HybridHits
common_noise_hname_hybrid_level_bottom:
 - HybridHitsBottom
common_noise_hname_hybrid_level_top:
 - HybridHitsTop

# common noise histogram names (chip level)
common_noise_hname_chip_level:
 - ChipHits
common_noise_hname_chip_level_bottom:
 - ChipHitsBottom
common_noise_hname_chip_level_top:
 - ChipHitsTop

# common noise module level
common_noise_hname_module_level:
 - ModuleHits
common_noise_hname_module_level_bottom:
 - ModuleHitsBottom
common_noise_hname_module_level_top:
 - ModuleHitsTop

# pedestal at CBC level
pede_hname_chip_level:
 - ChannelPedestal
 - ChannelPedestalDistribution





files:
  2S_18_6_KIT-10019:
    Run1:
      tfile_main: /Users/gsaha/Work/IPHC/TrackerUpgrade/Inputs/Results_QuickTests_KIT_May15/Ref_KIT_QuickTests/Ref_2S_18_6_KIT-10019.root
      tfile_dqm: /Users/gsaha/Work/IPHC/TrackerUpgrade/Inputs/Results_QuickTests_KIT_May15/Ref_KIT_QuickTests/Ref_2S_18_6_KIT-10019.root
  2S_18_6_KIT-10018:
    Run1:
      tfile_main: /Users/gsaha/Work/IPHC/TrackerUpgrade/Inputs/Results_QuickTests_KIT_May15/Ref_KIT_QuickTests/Ref_2S_18_6_KIT-10018.root
      tfile_dqm: /Users/gsaha/Work/IPHC/TrackerUpgrade/Inputs/Results_QuickTests_KIT_May15/Ref_KIT_QuickTests/Ref_2S_18_6_KIT-10018.root
  2S_18_6_KIT-10017:
    Run1:
      tfile_main: /Users/gsaha/Work/IPHC/TrackerUpgrade/Inputs/Results_QuickTests_KIT_May15/Ref_KIT_QuickTests/Ref_2S_18_6_KIT-10017.root
      tfile_dqm: /Users/gsaha/Work/IPHC/TrackerUpgrade/Inputs/Results_QuickTests_KIT_May15/Ref_KIT_QuickTests/Ref_2S_18_6_KIT-10017.root
  2S_18_6_KIT-10009:
    Run1:
      tfile_main: /Users/gsaha/Work/IPHC/TrackerUpgrade/Inputs/Results_QuickTests_KIT_May15/Ref_KIT_QuickTests/Ref_2S_18_6_KIT-10009.root
      tfile_dqm: /Users/gsaha/Work/IPHC/TrackerUpgrade/Inputs/Results_QuickTests_KIT_May15/Ref_KIT_QuickTests/Ref_2S_18_6_KIT-10009.root
  2S_18_6_KIT-10013:
    Run1:
      tfile_main: /Users/gsaha/Work/IPHC/TrackerUpgrade/Inputs/Results_QuickTests_KIT_May15/Ref_KIT_QuickTests/Ref_2S_18_6_KIT-10013.root
      tfile_dqm: /Users/gsaha/Work/IPHC/TrackerUpgrade/Inputs/Results_QuickTests_KIT_May15/Ref_KIT_QuickTests/Ref_2S_18_6_KIT-10013.root
  2S_18_6_KIT-10015:
    Run1:
      tfile_main: /Users/gsaha/Work/IPHC/TrackerUpgrade/Inputs/Results_QuickTests_KIT_May15/Ref_KIT_QuickTests/Ref_2S_18_6_KIT-10015.root
      tfile_dqm: /Users/gsaha/Work/IPHC/TrackerUpgrade/Inputs/Results_QuickTests_KIT_May15/Ref_KIT_QuickTests/Ref_2S_18_6_KIT-10015.root
  2S_18_6_KIT-10011:
    Run1:
      tfile_main: /Users/gsaha/Work/IPHC/TrackerUpgrade/Inputs/Results_QuickTests_KIT_May15/Ref_KIT_QuickTests/Ref_2S_18_6_KIT-10011.root
      tfile_dqm: /Users/gsaha/Work/IPHC/TrackerUpgrade/Inputs/Results_QuickTests_KIT_May15/Ref_KIT_QuickTests/Ref_2S_18_6_KIT-10011.root
  2S_18_6_KIT-10010:
    Run1:
      tfile_main: /Users/gsaha/Work/IPHC/TrackerUpgrade/Inputs/Results_QuickTests_KIT_May15/Ref_KIT_QuickTests/Ref_2S_18_6_KIT-10010.root
      tfile_dqm: /Users/gsaha/Work/IPHC/TrackerUpgrade/Inputs/Results_QuickTests_KIT_May15/Ref_KIT_QuickTests/Ref_2S_18_6_KIT-10010.root
  2S_18_6_KIT-10008:
    Run1:
      tfile_main: /Users/gsaha/Work/IPHC/TrackerUpgrade/Inputs/Results_QuickTests_KIT_May15/Ref_KIT_QuickTests/Ref_2S_18_6_KIT-10008.root
      tfile_dqm: /Users/gsaha/Work/IPHC/TrackerUpgrade/Inputs/Results_QuickTests_KIT_May15/Ref_KIT_QuickTests/Ref_2S_18_6_KIT-10008.root
  2S_18_6_KIT-10007:
    Run1:
      tfile_main: /Users/gsaha/Work/IPHC/TrackerUpgrade/Inputs/Results_QuickTests_KIT_May15/Ref_KIT_QuickTests/Ref_2S_18_6_KIT-10007.root
      tfile_dqm: /Users/gsaha/Work/IPHC/TrackerUpgrade/Inputs/Results_QuickTests_KIT_May15/Ref_KIT_QuickTests/Ref_2S_18_6_KIT-10007.root
  2S_18_6_KIT-10020:
    Run1:
      tfile_main: /Users/gsaha/Work/IPHC/TrackerUpgrade/Inputs/Results_QuickTests_KIT_May15/Ref_KIT_QuickTests/Ref_2S_18_6_KIT-10020.root
      tfile_dqm: /Users/gsaha/Work/IPHC/TrackerUpgrade/Inputs/Results_QuickTests_KIT_May15/Ref_KIT_QuickTests/Ref_2S_18_6_KIT-10020.root
  2S_18_6_KIT-10016:
    Run1:
      tfile_main: /Users/gsaha/Work/IPHC/TrackerUpgrade/Inputs/Results_QuickTests_KIT_May15/Ref_KIT_QuickTests/Ref_2S_18_6_KIT-10016.root
      tfile_dqm: /Users/gsaha/Work/IPHC/TrackerUpgrade/Inputs/Results_QuickTests_KIT_May15/Ref_KIT_QuickTests/Ref_2S_18_6_KIT-10016.root

output: /Users/gsaha/Work/IPHC/TrackerUpgrade/Output