maintag: IPHC_singleModuleBox

ladder: no
single_module_box: yes

n_boards: 1
n_opticals: 1


# strip noise histogram names (hybrid level)
strip_noise_hname_hybrid_level: StripChannelNoise
strip_noise_hname_hybrid_level_bottom: StripChannelNoiseBottom
strip_noise_hname_hybrid_level_top: StripChannelNoiseTop

# strip noise histogram names (chip level)
strip_noise_hname_chip_level: ChannelNoise
strip_noise_hname_chip_level_bottom: ChannelNoiseBottom
strip_noise_hname_chip_level_top: ChannelNoiseTop

# common noise histogram names (hybrid level)
common_noise_hname_hybrid_level: CommonNoiseHits_SigmaNoise_0.000
common_noise_hname_hybrid_level_bottom: CommonNoiseHitsBottom_SigmaNoise_0.000
common_noise_hname_hybrid_level_top: CommonNoiseHitsTop_SigmaNoise_0.000

# common noise histogram names (chip level)
common_noise_hname_chip_level: CommonNoiseHits_SigmaNoise_0.000
common_noise_hname_chip_level_bottom: CommonNoiseHitsBottom_SigmaNoise_0.000
common_noise_hname_chip_level_top: CommonNoiseHitsTop_SigmaNoise_0.000

# common noise module level
common_noise_hname_module_level: CommonNoiseHits_SigmaNoise_0.000
common_noise_hname_module_level_bottom: CommonNoiseHitsBottom_SigmaNoise_0.000
common_noise_hname_module_level_top: CommonNoiseHitsTop_SigmaNoise_0.000


files:
  2S_18_6_KIT-10019:
    Run1:
      tfile_main: /Users/gsaha/Work/IPHC/TrackerUpgrade/Inputs/Results_QuickTests_KIT_May15/Results_2S_18_6_KIT-10019/Results.root
      tfile_dqm: /Users/gsaha/Work/IPHC/TrackerUpgrade/Inputs/Results_QuickTests_KIT_May15/Results_2S_18_6_KIT-10019/MonitorDQM_2025-05-15_09-13-16.root
  2S_18_6_KIT-10018:
    Run1:  
      tfile_main: /Users/gsaha/Work/IPHC/TrackerUpgrade/Inputs/Results_QuickTests_KIT_May15/Results_2S_18_6_KIT-10018/Results.root
      tfile_dqm: /Users/gsaha/Work/IPHC/TrackerUpgrade/Inputs/Results_QuickTests_KIT_May15/Results_2S_18_6_KIT-10018/MonitorDQM_2025-05-15_09-41-23.root
  2S_18_6_KIT-10017:
    Run1:
      tfile_main: /Users/gsaha/Work/IPHC/TrackerUpgrade/Inputs/Results_QuickTests_KIT_May15/Results_2S_18_6_KIT-10017/Results.root
      tfile_dqm: /Users/gsaha/Work/IPHC/TrackerUpgrade/Inputs/Results_QuickTests_KIT_May15/Results_2S_18_6_KIT-10017/MonitorDQM_2025-05-15_09-57-47.root
  2S_18_6_KIT-10009:
    Run1:
      tfile_main: /Users/gsaha/Work/IPHC/TrackerUpgrade/Inputs/Results_QuickTests_KIT_May15/Results_2S_18_6_KIT-10009/Results.root
      tfile_dqm: /Users/gsaha/Work/IPHC/TrackerUpgrade/Inputs/Results_QuickTests_KIT_May15/Results_2S_18_6_KIT-10009/MonitorDQM_2025-05-15_10-09-54.root
  2S_18_6_KIT-10016:
    Run1:
      tfile_main: /Users/gsaha/Work/IPHC/TrackerUpgrade/Inputs/Results_QuickTests_KIT_May15/Results_2S_18_6_KIT-10016/Results.root
      tfile_dqm: /Users/gsaha/Work/IPHC/TrackerUpgrade/Inputs/Results_QuickTests_KIT_May15/Results_2S_18_6_KIT-10016/MonitorDQM_2025-05-15_10-20-24.root
  2S_18_6_KIT-10015:
    Run1:
      tfile_main: /Users/gsaha/Work/IPHC/TrackerUpgrade/Inputs/Results_QuickTests_KIT_May15/Results_2S_18_6_KIT-10015/Results.root
      tfile_dqm: /Users/gsaha/Work/IPHC/TrackerUpgrade/Inputs/Results_QuickTests_KIT_May15/Results_2S_18_6_KIT-10015/MonitorDQM_2025-05-16_11-13-39.root
  2S_18_6_KIT-10011:
    Run1:
      tfile_main: /Users/gsaha/Work/IPHC/TrackerUpgrade/Inputs/Results_QuickTests_KIT_May15/Results_2S_18_6_KIT-10011/Results.root
      tfile_dqm: /Users/gsaha/Work/IPHC/TrackerUpgrade/Inputs/Results_QuickTests_KIT_May15/Results_2S_18_6_KIT-10011/MonitorDQM_2025-05-14_15-34-12.root
  2S_18_6_KIT-10010:
    Run1:
      tfile_main: /Users/gsaha/Work/IPHC/TrackerUpgrade/Inputs/Results_QuickTests_KIT_May15/Results_2S_18_6_KIT-10010/Results.root
      tfile_dqm: /Users/gsaha/Work/IPHC/TrackerUpgrade/Inputs/Results_QuickTests_KIT_May15/Results_2S_18_6_KIT-10010/MonitorDQM_2025-05-14_15-46-41.root
  2S_18_6_KIT-10008:
    Run1:
      tfile_main: /Users/gsaha/Work/IPHC/TrackerUpgrade/Inputs/Results_QuickTests_KIT_May15/Results_2S_18_6_KIT-10008/Results.root
      tfile_dqm: /Users/gsaha/Work/IPHC/TrackerUpgrade/Inputs/Results_QuickTests_KIT_May15/Results_2S_18_6_KIT-10008/MonitorDQM_2025-05-14_16-00-20.root
  2S_18_6_KIT-10007:
    Run1:
      tfile_main: /Users/gsaha/Work/IPHC/TrackerUpgrade/Inputs/Results_QuickTests_KIT_May15/Results_2S_18_6_KIT-10007/Results.root
      tfile_dqm: /Users/gsaha/Work/IPHC/TrackerUpgrade/Inputs/Results_QuickTests_KIT_May15/Results_2S_18_6_KIT-10007/MonitorDQM_2025-05-14_16-12-37.root
  2S_18_6_KIT-10020:
    Run1:
      tfile_main: /Users/gsaha/Work/IPHC/TrackerUpgrade/Inputs/Results_QuickTests_KIT_May15/Results_2S_18_6_KIT-10020/Results.root
      tfile_dqm: /Users/gsaha/Work/IPHC/TrackerUpgrade/Inputs/Results_QuickTests_KIT_May15/Results_2S_18_6_KIT-10020/MonitorDQM_2025-05-15_08-59-22.root
  2S_18_6_KIT-10013:
    Run1:
      tfile_main: /Users/gsaha/Work/IPHC/TrackerUpgrade/Inputs/Results_QuickTests_KIT_May15/Results_2S_18_6_KIT-10013/Results.root
      tfile_dqm: /Users/gsaha/Work/IPHC/TrackerUpgrade/Inputs/Results_QuickTests_KIT_May15/Results_2S_18_6_KIT-10013/MonitorDQM_2025-05-14_15-09-57.root

output: /Users/gsaha/Work/IPHC/TrackerUpgrade/Output